import React, { useState } from 'react';
import { Card } from '../../../components/ui/Card';
import { Button } from '../../../components/ui/Button';
import { Select } from '../../../components/ui/Select';
import { Input } from '../../../components/ui/Input';
import { Table } from '../../../components/ui/Table';
import { Badge } from '../../../components/ui/Badge';
import {
  FileTextIcon,
  DownloadIcon,
  CalendarIcon,
  BarChartIcon,
  ShieldCheckIcon,
  UsersIcon } from
'lucide-react';
const recentReportsData = [
{
  id: '1',
  name: 'Data Integrity Report',
  generatedBy: 'System',
  date: '20-Feb-2025',
  format: 'PDF',
  size: '1.2 MB'
},
{
  id: '2',
  name: 'User Activity Summary',
  generatedBy: 'Admin',
  date: '19-Feb-2025',
  format: 'Excel',
  size: '450 KB'
},
{
  id: '3',
  name: 'Module Usage Stats',
  generatedBy: 'Principal',
  date: '15-Feb-2025',
  format: 'CSV',
  size: '120 KB'
},
{
  id: '4',
  name: 'Pending Approvals',
  generatedBy: 'Admin',
  date: '10-Feb-2025',
  format: 'PDF',
  size: '800 KB'
},
{
  id: '5',
  name: 'Security Audit Log',
  generatedBy: 'System',
  date: '01-Feb-2025',
  format: 'Excel',
  size: '2.5 MB'
}];

export function AdministrativeControlReports() {
  const [reportType, setReportType] = useState('');
  const [format, setFormat] = useState('pdf');
  const columns = [
  {
    key: 'name',
    header: 'Report Name',
    render: (row: any) => <span className="font-medium">{row.name}</span>
  },
  {
    key: 'generatedBy',
    header: 'Generated By'
  },
  {
    key: 'date',
    header: 'Date'
  },
  {
    key: 'format',
    header: 'Format',
    render: (row: any) => <Badge variant="secondary">{row.format}</Badge>
  },
  {
    key: 'size',
    header: 'Size'
  },
  {
    key: 'actions',
    header: 'Actions',
    render: () =>
    <Button
      variant="ghost"
      size="sm"
      leftIcon={<DownloadIcon className="w-3 h-3" />}>

          Download
        </Button>

  }];

  const reportCategories = [
  {
    title: 'Data Integrity',
    value: '3 Issues',
    icon: <ShieldCheckIcon className="w-5 h-5 text-red-500" />,
    color: 'bg-red-50'
  },
  {
    title: 'User Activity',
    value: '234 Active',
    icon: <UsersIcon className="w-5 h-5 text-blue-500" />,
    color: 'bg-blue-50'
  },
  {
    title: 'Module Usage',
    value: 'Student Mgmt',
    icon: <BarChartIcon className="w-5 h-5 text-green-500" />,
    color: 'bg-green-50'
  },
  {
    title: 'Pending Approvals',
    value: '17 Pending',
    icon: <FileTextIcon className="w-5 h-5 text-orange-500" />,
    color: 'bg-orange-50'
  }];

  return (
    <div className="p-6 space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">
            Administrative Control Reports
          </h1>
          <p className="text-sm text-gray-500">
            Generate and view system-wide administrative reports
          </p>
        </div>
        <Button
          variant="outline"
          leftIcon={<DownloadIcon className="w-4 h-4" />}>

          Export All
        </Button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {reportCategories.map((cat, index) =>
        <Card key={index} className="p-4">
            <div className="flex items-center gap-4">
              <div className={`p-3 rounded-lg ${cat.color}`}>{cat.icon}</div>
              <div>
                <p className="text-sm text-gray-500">{cat.title}</p>
                <p className="text-lg font-bold text-gray-900">{cat.value}</p>
              </div>
            </div>
          </Card>
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Card title="Quick Report Generation" className="lg:col-span-1">
          <div className="space-y-4">
            <Select
              label="Report Type"
              value={reportType}
              onChange={setReportType}
              options={[
              {
                value: '',
                label: 'Select Report Type'
              },
              {
                value: 'integrity',
                label: 'Data Integrity Report'
              },
              {
                value: 'activity',
                label: 'User Activity Summary'
              },
              {
                value: 'usage',
                label: 'Module Usage Statistics'
              },
              {
                value: 'approvals',
                label: 'Pending Approvals Summary'
              }]
              } />

            <div className="grid grid-cols-2 gap-2">
              <Input type="date" label="From Date" />
              <Input type="date" label="To Date" />
            </div>
            <Select
              label="Format"
              value={format}
              onChange={setFormat}
              options={[
              {
                value: 'pdf',
                label: 'PDF Document'
              },
              {
                value: 'excel',
                label: 'Excel Spreadsheet'
              },
              {
                value: 'csv',
                label: 'CSV File'
              }]
              } />

            <div className="pt-2 flex gap-2">
              <Button variant="primary" className="flex-1">
                Generate Report
              </Button>
              <Button variant="outline" className="flex-1">
                Schedule
              </Button>
            </div>
          </div>
        </Card>

        <Card title="Recent Reports" className="lg:col-span-2">
          <Table columns={columns} data={recentReportsData} />
        </Card>
      </div>
    </div>);

}